#if !defined(TEMPORAL_VECTOR_INCLUDED_CHECK)
#define TEMPORAL_VECTOR_INCLUDED_CHECK

	cbuffer	taa_globals
	{
		float4 taa_jitter; 		// .xy - current jitter, .zw - previous jitter
	}

	// Add jitter for rasterizer pos
	void update_taa_vertex(inout float4 hpos)
	{
		#ifdef USE_TAA
			hpos.xy += taa_jitter.xy * hpos.ww;
		#endif
	}

	// Remove jitter which generated by update_taa_vertex()
	void update_taa_tc(inout float2 tc)
	{
		#ifdef USE_TAA
			tc += taa_jitter.xy * float2( 0.5, -0.5);
		#endif
	}

#endif
